version: "3.9"

services:
  mysql:
    image: mysql
    container_name: PyBoss_MySQL
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: PyBoss
    ports:
      - 127.0.0.1:3306:3306
  bot:
    container_name: PyBoss_Bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pyboss/logs:/PyBoss/pyboss/logs
      - .:/PyBoss
    env_file:
      - .env
    environment:
      ENVIRONMENT: production
      DATABASE_URL: mysql+mysqlconnector://root@mysql:3306/PyBoss
    depends_on:
      - mysql
