version: '3.9'

services:
  bot:
    build: .
    container_name: PyBoss_bot
    command: python PyBoss.py
    depends_on:
      - db
    volumes:
    - .:/PyBoss
  db:
    image: mysql
    container_name: MySQL
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
