version: 3.9

services:
  mysql:
    image: mysql
    container_name: PyBoss_MySQL
    environment:
      MYSQL_ALLOW_NO_PASSWORD: yes
      MYSQL_DATABASE: PyBoss
    ports:
      - 127.0.0.1:3306:3306
  bot:
    container_name: PyBoss_Bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot/logs:/PyBoss/bot/logs
      - .:/PyBoss
    env_file:
      - .env
    environment:
      ENVIRONMENT: production
      DATABASE_URL: mysql+mysqlconnector://root@db:3306/PyBoss"
    depends_on:
      - mysql
