version: '3.9'

services:
  mysql:
    image: mysql
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
  bot:
    container_name: PyBoss_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/PyBoss/logs
      - .:/PyBoss
    env_file:
      - .env
    environment:
      ENVIRONMENT = production
    depends_on:
      - mysql
