version = 1

[formatters]
    [formatters.simple]
    format = "%(levelname)s: %(name)s - %(asctime)s -> %(message)s"
    datefmt = "%H:%M:%S"

    [formatters.verbose]
    format = "%(levelname)s: %(name)s - %(asctime)s -> %(message)s"
    datefmt = "%d/%m/%Y (%H:%M:%S)"

[handlers]
    [handlers.console]
    class = "logging.StreamHandler"
    formatter = "simple"
    level = "INFO"
    stream = "ext://sys.stdout"

    [handlers.file]
    class = "logging.handlers.RotatingFileHandler"
    formatter = "verbose"
    level = "DEBUG"
    filename = "bot/logs/bot.log"
    maxBytes = 50_000  # 50KB
    backupCount = 4

[loggers]
    [loggers.root]  # The default logger used for production
    level = "WARNING"
    handlers = ["console"]

    [loggers.development]
    level = "DEBUG"
    handlers = ["console", "file"]